import type { Metadata } from "next";
import { Geist, Geist_Mono} from "next/font/google";
import { Russo_One,Abril_Fatface  } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const russo = Russo_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-russo-one', 
  display: 'swap',
});

export const abril = Abril_Fatface({
  subsets: ['latin'],
  weight: '400', 
  variable: '--font-abril-fatface', 
  display: 'swap',
});

export const metadata: Metadata = { 
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${russo.variable} ${abril.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
          {children}
      </body>
    </html>
  );
}
